/** Smogon's Champions move / item / ability reference, generated by scripts/smogon.mjs. */

export interface RefMove {
  name: string;
  type: string;
  category: 'Physical' | 'Special' | 'Status';
  power: number;
  accuracy: number; // 0 = never misses
  pp: number;
  priority: number;
  target: string;
  description: string;
}
export interface RefEntry {
  name: string;
  description: string;
}
export interface Reference {
  updatedAt: string;
  moves: RefMove[];
  items: RefEntry[];
  abilities: RefEntry[];
}

export async function loadReference(): Promise<Reference> {
  const res = await fetch(`${import.meta.env.BASE_URL}data/smogon.json`);
  if (!res.ok) throw new Error('smogon.json missing - run "npm run scrape"');
  return (await res.json()) as Reference;
}

const TARGETS: Record<string, string> = {
  Normal: 'One target',
  Any: 'One target (any range)',
  Self: 'User',
  AdjacentAlly: 'An ally',
  AdjacentAllyOrSelf: 'An ally or user',
  AdjacentFoe: 'One foe',
  AllAdjacent: 'All adjacent',
  AllAdjacentFoes: 'Both foes',
  Allies: 'User and allies',
  AllySide: 'Your side',
  AllyTeam: 'Your team',
  FoeSide: "Foe's side",
  All: 'Whole field',
  RandomNormal: 'Random foe',
  Scripted: 'Last attacker',
  Field: 'Whole field',
};
export const targetLabel = (t: string): string => TARGETS[t] ?? t;

// Smogon writes multipliers as "1.5×"; treat × as a plain x so typing "1.5x" works.
const norm = (s: string) => s.toLowerCase().replace(/×/g, 'x');


/**
 * Words must all appear in the name or the description (case-insensitive), so "lowers speed" finds Icy Wind
 * and "1.5x" finds boosting items. Name matches come first, prefix matches before the rest.
 */
export function searchEntries<T extends { name: string; description: string }>(list: T[], query: string): T[] {
  // Match on word stems so "lowers" / "lowering" also find text that says "lower" (and "raises" finds "raise").
  const stem = (w: string) => (w.length > 5 && w.endsWith('ing') ? w.slice(0, -3) : w.length > 3 && w.endsWith('s') && !w.endsWith('ss') ? w.slice(0, -1) : w);
  const words = norm(query).split(/\s+/).filter(Boolean).map(stem);
  if (!words.length) return list;
  const scored: [number, T][] = [];
  for (const e of list) {
    const name = norm(e.name);
    const text = `${name} ${norm(e.description)}`;
    if (!words.every((w) => text.includes(w))) continue;
    const inName = words.every((w) => name.includes(w));
    scored.push([inName ? (name.startsWith(words[0]) ? 0 : 1) : 2, e]);
  }
  return scored.sort((a, b) => a[0] - b[0] || a[1].name.localeCompare(b[1].name)).map(([, e]) => e);
}
